import nodemailer from 'nodemailer';

const smtpUser = process.env.SMTP_USER;
const smtpPass = process.env.SMTP_PASS;
const smtpHost = process.env.SMTP_HOST || 'smtp.gmail.com';
const smtpPort = parseInt(process.env.SMTP_PORT || '587');
const emailFrom = process.env.EMAIL_FROM || 'noreply@skyviontech.com';

let transporter: nodemailer.Transporter | null = null;
if (smtpUser && smtpPass && !smtpUser.includes('your-email')) {
  transporter = nodemailer.createTransport({
    host: smtpHost,
    port: smtpPort,
    secure: smtpPort === 465,
    auth: {
      user: smtpUser,
      pass: smtpPass,
    },
  });
}

interface EmailOptions {
  to: string;
  subject: string;
  html: string;
}

export async function sendEmail(options: EmailOptions): Promise<boolean> {
  const mailOptions = {
    from: emailFrom,
    to: options.to,
    subject: options.subject,
    html: options.html,
  };

  if (transporter) {
    try {
      await transporter.sendMail(mailOptions);
      console.log(`[Email] Email sent successfully to ${options.to}`);
      return true;
    } catch (error) {
      console.error('[Email] Failed to send email via SMTP:', error);
    }
  }

  // Fallback / Mock log
  console.log('\n📧 ─────────────────── [MOCK EMAIL SENT] ───────────────────');
  console.log(`FROM:    ${emailFrom}`);
  console.log(`TO:      ${options.to}`);
  console.log(`SUBJECT: ${options.subject}`);
  console.log('BODY:');
  console.log(options.html.replace(/<[^>]*>/g, ' ').replace(/\s+/g, ' ').trim());
  console.log('──────────────────────────────────────────────────────────\n');
  return true;
}

export function getBookingConfirmationTemplate(name: string, date: string, time: string, timezone: string): string {
  return `
    <div style="font-family: Arial, sans-serif; background-color: #F5F9FF; padding: 20px; border-radius: 12px;">
      <h2 style="color: #4F7DF3; margin-bottom: 10px;">SkyVoice Appointment Confirmed</h2>
      <p>Hello <strong>${name}</strong>,</p>
      <p>Your voice scheduling session has successfully booked an appointment on our calendar.</p>
      <div style="background-color: white; border: 1px solid #E2E8F0; padding: 15px; border-radius: 8px; margin: 15px 0;">
        <p style="margin: 5px 0;">📅 <strong>Date:</strong> ${date}</p>
        <p style="margin: 5px 0;">⏰ <strong>Time:</strong> ${time}</p>
        <p style="margin: 5px 0;">🌐 <strong>Timezone:</strong> ${timezone}</p>
      </div>
      <p>If you need to reschedule or cancel, you can do so by calling back or via the dashboard.</p>
      <p style="font-size: 12px; color: #94A3B8; margin-top: 20px;">Powered by SKYVION AI Voice Operations Platform</p>
    </div>
  `;
}

export function getProjectInquiryTemplate(companyName: string, requirements: string, budget: string, timeline: string, email: string): string {
  return `
    <div style="font-family: Arial, sans-serif; background-color: #F5F9FF; padding: 20px; border-radius: 12px;">
      <h2 style="color: #4F7DF3; margin-bottom: 10px;">New Project Inquiry Captured</h2>
      <p>A new client lead was generated by the SkyVoice AI Assistant.</p>
      <div style="background-color: white; border: 1px solid #E2E8F0; padding: 15px; border-radius: 8px; margin: 15px 0;">
        <p style="margin: 5px 0;">🏢 <strong>Company Name:</strong> ${companyName}</p>
        <p style="margin: 5px 0;">✉️ <strong>Client Email:</strong> ${email}</p>
        <p style="margin: 5px 0;">💼 <strong>Timeline:</strong> ${timeline}</p>
        <p style="margin: 5px 0;">💰 <strong>Budget Range:</strong> ${budget}</p>
        <p style="margin: 10px 0 5px 0;">📝 <strong>Requirements:</strong></p>
        <div style="background-color: #F8FAFC; padding: 10px; border-radius: 4px; font-size: 14px; border-left: 3px solid #4F7DF3;">
          ${requirements}
        </div>
      </div>
      <p style="font-size: 12px; color: #94A3B8; margin-top: 20px;">Lead saved in SkyVoice MongoDB system</p>
    </div>
  `;
}
